### PR TITLE
[SUGGESTION] Too many logs

### PR DESCRIPTION
**Pull request by stefdworschak**
**Description:**
Implementing a new logging approach whereby all logs are at `logging.INFO` level at the lowest and logs starting with `Important:` will be filtered and logged into a log file.

Currently only implemented for `source/axie/payments.py`.

**Testing:**
All tests passing successfully.

### CODE REVIEW

**Comment by FerranMarin** [comment]
Hello Stefan,

Thank you for your PR and for finding the last bits we missed this morning! It was a pleasure working through this together :)
Feel free to come pick up more tickets if you feel like it ;)

Regards,
Ferran

**Comment by stefdworschak** [comment]
Cool! :sunglasses: I'll have a look if I can find something I can contribute to.

**Comment by FerranMarin** [comment]
Any tickets are fair game. Else join the discord, we are constantly
discussing stuff to do.

**Comment by FerranMarin** [comment]
Btw, I've implemented this bit in claims too in my latest release.

**Pull request merged**
